### ISSUE TITLE
Do not generate public links

### ISSUE THREAD

**Issue by qimlisky** [tyc0on/GPT-SoVITS-colab#5]
Log:ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires kaleido, which is not installed.
Successfully installed Faster_Whisper-0.10.0 LangSegment-0.1.3 addict-2.4.0 aiofiles-23.2.1 aliyun-python-sdk-core-2.14.0 aliyun-python-sdk-kms-2.16.2 antlr4-python3-runtime-4.9.3 av-10.0.0 cn2an-0.5.22 coloredlogs-15.0.1 crcmod-1.7 ctranslate2-3.24.0 cython-0.29.37 datasets-2.16.1 dill-0.3.7 distance-0.1.3 einops-0.7.0 fastapi-0.109.2 ffmpeg-python-0.2.0 ffmpy-0.3.1 funasr-1.0.0 g2p_en-2.1.0 gradio-3.38.0 gradio_client-0.8.1 h11-0.14.0 hdbscan-0.8.33 httpcore-1.0.2 httpx-0.26.0 humanfriendly-10.0 hydra-core-1.3.2 jaconv-0.3.4 jamo-0.4.1 jieba_fast-0.53 jmespath-0.10.0 kaldiio-2.18.0 librosa-0.9.2 lightning-utilities-0.10.1 markdown-it-py-2.2.0 mdit-py-plugins-0.3.3 modelscope-1.10.0 multiprocess-0.70.15 omegaconf-2.3.0 onnxruntime-1.17.0 orjson-3.9.13 oss2-2.18.4 proces-0.1.7 py3langid-0.2.2 pycryptodome-3.20.0 pydub-0.25.1 pyopenjtalk-0.3.3 pypinyin-0.50.0 python-multipart-0.0.7 pytorch-lightning-2.1.4 pytorch-wpe-0.0.1 resampy-0.4.2 semantic-version-2.10.0 simplejson-3.19.2 starlette-0.36.3 torch-complex-0.4.3 torchmetrics-1.3.0.post0 umap-0.1.1 uvicorn-0.27.0.post1 websockets-11.0.3 yapf-0.40.2
WARNING: The following packages were previously imported in this runtime:
  [pydevd_plugins]
You must restart the runtime in order to use newly installed versions.
Running on local URL:  http://0.0.0.0:9874

**Comment by tyc0on** [comment]
the gradio link comes after that link
